name: CI/CD Pipeline

on:
  push:
    branches:
      - cli_to_RDS
  pull_request:
    branches:
      - cli_to_RDS

jobs:
  validate:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.8.0"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install python-dotenv
        run: pip install python-dotenv

      - name: Setup .env file and Install Dependencies
        run: |
          echo "GITHUB_TOKEN=${{ secrets.API_TOKEN }}" >> checker/.env
          echo "LOG_LEVEL=info" >> checker/.env
          echo "LOG_FILE=/tmp/checker.log" >> checker/.env

      - name: Run checker script
        run: python3 checker/checker.py

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Install dependencies
        run: npm install

      # - name: Copy node_modules to EC2
      #   env:
      #     NODE_ENV: production
      #   run: |
      #     scp -o StrictHostKeyChecking=no -r node_modules ec2-user@ec2-107-23-20-150.compute-1.amazonaws.com:/ECE-461-Phase-2

      - name: Deploy Code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-107-23-20-150.compute-1.amazonaws.com '
          cd /ECE-461-Phase-2 &&
          git pull &&
          npm install --production &&
          ./run build
          '